# -*- coding: utf-8 -*-
"""11 - Lambda functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2lwoZXj2qmgGE4evWq-ho06RFRzrhyD

# Beginner
"""

# add 2 numbers
val = lambda x, y: x + y
val(2, 3)

# Square of a number
val = lambda x: x**2
val(4)

# even number
val = lambda x: x % 2 == 0
print(val(3))
print(val(4))
print(val(0))

# Sort by the second index value of tuples
tuples = [(1, 2), (4, 2), (4, 6), (5, 1)]
sorted = sorted(tuples, key = lambda x: x[1])
print(sorted)

# larger of two number
islarger = lambda x, y: x if x > y else y
print(islarger(1, 10))

# Double the numbers in list
lister = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
double = list(map(lambda x: x * 2, lister))
print(double)

# filter the odd numbers using lambda
lister = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
odd = list(filter(lambda x: x % 2 == 1, lister))
print(odd)

# reverse a string
reverse_string = lambda s: s[::-1]
print(reverse_string("mohanraj"))

# Multiply all values in list using reduce
from functools import reduce
lister = [2, 4, 6, 10]
reducer = reduce(lambda x, y: x * y, lister)
print(reducer)

# convert list of strings to uppercase
words = ["apple", "banana", "cherry"]
upper = list(map(lambda x: x.upper(), words))
print(upper)

"""#Intermediate"""

# Sort by perticular dictionary key
dictionary = [{"name": "mohan", "age": 18},{"name": "raj", "age": 20}, {"name": "hari", "age": 21}, {"name": "rajan", "age": 30}, {"name": "rishi", "age": 23}]
sorted = sorted(dictionary, key = lambda x: x["age"])
print(sorted)

# list of squares for given range
squares = lambda start, end: list(map(lambda x: x ** 2, range(start, end + 1)))
print(squares(1, 9))

# Positive number from a list
lister = [-1, -2, 3, -12, 5, 1, 3, -9, 6, 7, -2, 22, 23, -23]
positive = list(filter(lambda x: x > 0, lister))
print(positive)

# max of 3 numbers
maxima = lambda x, y, z: max(x, y, z)
print(maxima(12, 6742, 121))

# Common value in 2 lists
list1 = [1, 4, 8, 9, 3, 2, 4, 6, 7, 0]
list2 = [0, 8, 6, 4, 2, 1, 4, 5, 7, 7]
common = list(filter(lambda x: x in list1, list2))
print(common)

# Sum of even numbers in list
from functools import reduce
lister = [1, 2, 3, 4, 5, 6, 7, 8, 9, 40]
sum = reduce(lambda x, y: x + y, filter(lambda z: z % 2 == 0, lister))
print(sum)

# sort by length of words in list
lister = ["appke", "banana", "cat", "dog", "elephant", "fanta", "nayagara", "zera", "zebronicsindian"]
sorter = __builtins__.sorted(lister, key = lambda x: len(x))
print(sorter)

# print the palindrome sfrom the words
words = ["dad", "mom", "akka", "radar", "level", "vigadakavi", "tenet", "nun", "soros"]
palindrome = list(filter(lambda x: x == x[::-1], words))
print(palindrome)

# Factorial of given number
fact = lambda n: reduce(lambda x, y: x * y, range(1, n + 1))
print(fact(5))