# -*- coding: utf-8 -*-
"""12 - File handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZdlBtZhgAwUXlQ07Ylcq3fJcJJ-d7WJd

#Beginner
"""

#Uploading the file via google colab
from google.colab import files
uploaded = files.upload()
uploaded = files.upload()

# reading a file
reader = open("GITHUB_HOST_LINKS_PYTHON.txt", "r")
print(reader.read())

reader1 = open("details.txt", "r")
reader2 = open("GITHUB_HOST_LINKS_PYTHON.txt", "r")
reader3 = open("password of paramedical.txt", "r")
print(reader1.read())
print(reader2.read())
print(reader3.read())

#read and write by "with" keyword
with open("details.txt", "w") as myfile:
  myfile.write("Name      : Mohanraj S \nAge       : 20 \nSchool    : National Higher Secondary School \nCity      : Gudiyattam")

with open("details.txt", "r") as myfile:
  detail_of_me = myfile.read()
print(detail_of_me)

# Download the files from google colab
from google.colab import files
files.download("details.txt")

# Read the uploaded files via google colab
from google.colab import files
uploaded_f = files.upload()

# check if the file name dynamically
details = list(uploaded.keys())[0]
print(details)

# Read the uploaded file
with open("details.txt", "r") as file:
  content = file.read()
print(content)

# Add a list to files
lister = ["apple", "banana", "cherry", "daddy", "elephant"]
with open("details.txt", "w") as add:
  for i in lister:
    add.write(i + "\n")

with open("details.txt", "r") as add:
  content = add.read()
print(content)

# unexpected file pening in google colab
try:
  with open("un.txt", "r") as file:
    content = file.read()
  print(content)
except FileNotFoundError:
  print("File Not found in Google Colab")

# Copy the content from one folder to another
from google.colab import files
uploaded = files.upload()
with open("details.txt" , "r") as source:
  content = source.read()
  print(content)
with open("duplicate.txt", "w") as destination:
  destination.write(content)

with open("duplicate.txt", "r") as readable:
  copied = readable.read()
print(copied)

"""#Intermediate

"""

# Raed 100 charachters of chunk like large files
from google.colab import files
uploaded = files.upload()
with open("details.txt", "r") as reader:
  while True:
    chunk = reader.read(100)
    if not chunk :
      break
    print(chunk)

# print the frequency of words
from collections import Counter
with open("details.txt", "r") as file:
  content = file.read()
  words = content.split()
  word_count = Counter(words)
  print(f"word       :       count\n")
  for i, j in word_count.items():
    print(f"{i}: {j}", end = "\n")

# Merge two files on other file
from google.colab import files
uploaded = files.upload()
uploaded = files.upload()
with open("details.txt", "r") as file1, open ("duplicate.txt", "r") as file2, open("destination.txt", "w") as merged_file:
  merged_file.write(file1.read())
  merged_file.write(file2.read())
  print("Files Merged Successfully")

with open("destination.txt", "r") as destiny:
  content = destiny.read()
print(content)

# Search a specific word in file
word = "Vellore"
linum = 0
with open("details.txt", "r") as file:
  for i in file:
    linum = linum + 1
    if word in i:
      print(f"{word} found in the {linum} : {i.strip()}")

# Find and replace text
with open("details.txt", "r") as file:
  content = file.read()
  new_content = content.replace("Vellore", "Gudiyattam")
with open("details.txt", "w") as file:
  file.write(new_content)
print("All occurence of 'Vellore' was replace with 'Gudiyattam' Successfully")

with open("details.txt", "r") as file:
  content = file.read()
  print(content)

# Remove duplicate lines
with open("details.txt", "r") as file:
  content = file.readlines()
  uline = list(set(content))

with open("details.txt", "w") as file:
  content = file.writelines(uline)
  print("Duplicate lines are remove successfully")
with open("details.txt","r") as file:
  content = file.read()
  print(content)

# read all line in reverse
with open("details.txt", "r") as file:
  content = file.readlines()
  for i in reversed(content):
    print(i.strip())

# Get size of the file
import os
filename = "details.txt"
size = os.path.getsize(filename)
print(f"Size of '{filename}' is '{size}' bytes")

# Calculate the number of line, word, charachter
line = 0
word = 0
char = 0
with open("details.txt", "r") as file:
  for i in file:
    line = line + 1
    words = i.split()
    word = word + len(words)
    char = char + len(i)

print(f"Number of lines : {line}")
print(f"Number of words : {word}")
print(f"Number of chars : {char}")