# -*- coding: utf-8 -*-
"""Modules and Libraries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SGzB5qw67FODv_zJNSXD3_kXaS08I7_i

#Beginner
"""

#math module()
import math
number = int(input("Enter the number : "))
square_root = math.sqrt(number)
print(square_root)

# Random module()
import random
rand = random.randint(1, 100)
print(rand)

# Datetime()
import datetime
current = datetime.datetime.now()
print(current)

# Particular module
from math import pi, sin
angular = pi / 2
print(round(angular), 2)
sin_value = sin(angular)
print(sin_value)

# Access External library
!pip install requests
import requests
response = requests.get('https://api.github.com')
print(f"The Status Code of that is : {response.status_code}")
print(f"The Txt content of the response : {response.text}")

# OS module()
import os
file_dir = os.listdir()
print(f"File_and Directeries : {file_dir}")

#Matplotlib()
!pip install matplotlib
import matplotlib.pyplot as plt

categary = ["a", "b", "c", "d", "e"]
values = [1, 2, 3, 4, 5]

plt.bar(categary, values)
plt.xlabel("Categaries")
plt.ylabel("Values")
plt.title("Bar Chart")
plt.show()

#Time mmodule()
import time
print("Wait for 5 seconds...")
time.sleep(5)
print("Hello world")

#Statistics module()
import statistics
data = [1, 1, 2, 3, 4, 5, 6, 7, 8, 1, 1, 2, 3, 4, 4, 5, 6, 7, 0]
mean = statistics.mean(data)
median = statistics.median(data)
mode = statistics.mode(data)

print(f"The Mean Value is : {round((mean), 2)}")
print(f"The Median Value is : {median}")
print(f"The Mode Value is : {mode}")

# Array Module()
import numpy as np
array = [[1, 2, 3], [4, 5, 6]]
print("Arry")
print(array)
arrau_sum = np.sum(array)
print(arrau_sum)

"""#Intermediate"""

#Line plot
import matplotlib.pyplot as plt
days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
temperature = [27, 28, 34, 29, 34, 25, 33]

plt.plot(days, temperature, marker = "o")
plt.xlabel("Days")
plt.ylabel("Temperatures °C")
plt.title("The Temperatures over a week")
plt.grid(True)
plt.show()

# Collections
from collections import Counter
sentence = "National higher Seconary School Gudiattam Vellore TamilNadu National higher Seconary School National higher Seconary School"
words = sentence.lower().split()
countedv = Counter(words)
print(countedv)

