# -*- coding: utf-8 -*-
"""1 - String Slicing and Indexing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sZQLo05dVZYy7iAXXXvO4gJvgolAWG-2
"""

a = input("Enter your String :")
print(a[0])

b = "hello world"
print(b[6:12])

s = "Python"
print(s[-1])

s = "abcdef"
print(s[2:5])

c = "National Higher Secondary School"
print(c[::-1])

d = "mohanraj"
print(d[:4])
print(d[0:])
print(d[-3:])

e = "123456789"
print(e[::-1])
print(e[::1])
print(e[::2])
print(e[1:-3])

f = "aaabbbcccdddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrssstttuuuvvvwwwxxxyyyzzz"
print(f[::3])

s = "Python Programming"
print(s[7:])

print(s[1::3])
print(s[::-2])

s.replace(s[0],"a")
print(s[::2])

x = "mohanraj"
print(x[1:-1][::-1])
x[len(x)//2-1:len(x)//2+1]
w = "mohan"
w[len(w)//2]

print(s)
s[2:-2:2]
print(s[:3]+s[-3:])
