# -*- coding: utf-8 -*-
"""3 - String Formatting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k0xz9JZhulUw3ChYi8IgZaFTRcQ9Eagm

##String Format method
"""

name = "mohan"
age = "22"
print("My name is {} and I am {} Years old".format(name, age))

"""##f - Strings"""

product = "Laptop"
price = "23000"
print(f"The Best product is {product} and the its price is {price}")

"""##String Padding"""

text = "mohan"
res = "{:>100}".format(text)
print(res)
print(len(res))

"""##Number Formatting

"""

pi = 3.1415926535
print(round(pi, 2))
print("{:.2f}".format(pi))

"""##Number Percentage"""

peer = 0.875
print("{:.1%}".format(peer))
print("{:.2%}".format(peer))

"""##Aligning Center"""

msg = "Hello"
prints = ("{:^20}".format(msg))
print(prints)
print(len(prints))

"""##Placeholders"""

person1 = "Mohan"
person2 = "Raj"
person3 = "Hari"
print("The Students names are {0}, {1}, {2}.".format(person1, person2, person3))

"""##Multiple variables in f-strings"""

mark1 = 15
mark2 = 15
mark3 = 15
mark4 = 15
mark5 = 15
total = mark1+mark2+mark3+mark4+mark5
print(f"The 5 subject Marks are {mark1}, {mark2}, {mark3}, {mark4}, {mark5} and the Total Mark is {total}.")

"""##Named arguments"""

ka = "raj"
ja = 19
print("Ravi shorted as {ka} and his age shorted as {ja}".format(ka = ka, ja = ja))

"""###Hexadecimal Formatting"""

num = 1234
print("{:x}".format(num))

"""#**Intermediate** **Questions**"""

from datetime import datetime
now = datetime(2024, 9, 29, 15, 45, 30)
my_formate = now.strftime("%d-%m-%Y %H-%M-%S")
print(my_formate)

"""###Padding with fill charachter"""

cus = "mohan"
print("{:-<15}".format(cus))
print("{:-^15}".format(cus))
print("{:->15}".format(cus))

"""###Dynamic width formatting"""

val = " National Higher "
inp = int(input("Enter Your width count"))
print("{:-^{}}".format(val, inp))

"""###Currency Fromating"""

cost = 10293927.235
print("{:,.2f}".format(cost))

"""###Signed with values"""

nume1 = -154.26
nume2 = 145.36
print("{:+.2f}".format(nume1))
print("{:+.2f}".format(nume2))

"""###Named placeholders with dictionaries"""

mydic = {"name": "mohanraj", "age": 21, "college": "Global Institute of Engineering and Technology"}
print("My name is {name} and my age is {age} then my college name is {college}".format(**mydic))

"""###Percentage Increase"""

old_value = 12232
new_value = 23293
in_out = (new_value-old_value)/100
print("{:.2f}%".format(in_out))

"""###HexaDecimal and Binary Conversion"""

user = int(input("Enter Your Value :"))
print("TheHexaDecimal value is :{:x}, \nThe Binary Value is :{:b}".format(user, user))