# -*- coding: utf-8 -*-
"""5 - List Methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17VkZc7mUayxLGR7hyBNcpkFi8TG27wmM

#Beginners

###Creating List
"""

list = [1, 2, 3, 4, 5, 7]
print(list)
lists = ["a", "b", "c", "d"]
print(lists)

"""###Accessing a list elements"""

print(list[2])
print(list[1])
print(list[0])
print(lists[0])

"""###Modifying list elements"""

list[0] = 10
lists[2] = "h"
print(list, lists)

"""###Appending list Elements"""

list.append(100)
lists.append("r")
print(list, lists)

"""###Inserting an element"""

list.insert(0, 1)
list.insert(6, 7)
lists.insert(2, "c")
lists.insert(4, "e")
print(list, lists)

"""###Removing a value"""

list.remove(10)
list.remove(7)
list.remove(100)
lists.remove("h")
lists.remove("r")
lists.remove("e")
print(list, lists)

"""###Popping an element"""

list.pop()
list.pop()
lists.pop()
lists.pop()
print(list, lists)

"""###Finding the Index of an element"""

print(list.index(1))
print(list.index(2))
print(list.index(4))
print(lists.index("a"))
print(lists.index("b"))

"""###Sorting a list"""

my = [7, 6, 4, 3, 2, 1]
print(my.sort())

"""###Reversing a list"""

print(my[::1])
print(my[::-1])

"""#Intermediate

###List Comprihension
"""

a = [1, 2, 3, 4, 5]
b = [i**2 for i in a]
print(b)
c = [j*5 for j in a]
print(c)

"""###Removing elements with del()"""

a = [0, 1, 2, 3, 4, 5, 6, 7]
del(a[0])
del(a[2])
print(a)

"""###Copy the list"""

list1 = [1, 2, 3, 4, 5]
listcopy = list1.copy()
print(listcopy)
listcopy[0] = 100
print(listcopy)

"""###List slicing"""

print(list1[3:])
print(list1[0:])
print(list1[2:4])
print(list1[1::2])

"""###List concatination"""

list_a = ["a", "b", "c", "d", "e"]
list_b = [1, 2, 3, 4, 5]
print(list_a + list_b)

"""###Extending a list"""

l1 = [1, 2, 3, 4, 5]
l2 = [5, 4, 3, 2, 1]
l2.extend(l1)
print(l1)
print(l2)

"""###List sorting in reverse"""

l2 = [3, 6, 1, 8, 9, 0, 3, 2, 4, 5, 6, 2, 1, 5, 7, 4]
print(l2)
l2.sort(reverse = True)
print(l2)

"""###List filter comprihension"""

lists = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Even_number = [i for i in lists if i%2 == 0]
odd_number = [i for i in lists if i!=0]
print(odd_number)
print(Even_number)


lists = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
new = []
for i in range(0, len(lists)):
  if i%2 == 0:
    lists.pop()
  else:
    new.append(i)
print(new)

"""###Inserting multiple elements in list"""

lo = [1, 2, 3, 4, 5, 6]
lo[3:3] = [10, 11, 12]
print(lo)
print(lo[5])