# -*- coding: utf-8 -*-
"""7 - Python Operators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LNuvM_J9IKBoUxBa4yrHk08q1R2az4-h

#Beginner

###Operator
"""

#Arithmatic Operator
a = 3
b = 2
c = 1
print(a+b*c)

#Modulo Operator
a = 10
b = 3
print(a % b)

#Exponential Operator
print(4**2)
print(5**3)
print(2**10)

#Floor Division
print(7 // 2)
print(25 // 4)

#Comparison Operator
a = 10
b = 20
print(a == b)
print(a != b)
print(a <= b)
print(a >= b)
print(a > b)
print(a < b)

#Logical Operator
result1 = True and False
result2 = True and True
result3 = True or False
result4 = True or True
print(f"result1 : {result1}")
print(f"result2 : {result2}")
print(f"result3 : {result3}")
print(f"result4 : {result4}")

#Membership Operator
list = [1, 2, 3]
print(1 in list)
print(1 not in list)

"""#Intermedite

###Chain Comparison operator
"""

res = 7 > 4 >= 2
print(res)
rese = 100 >= 100 >= 2
print(rese)

"""###Using `is` and `==`"""

a = [1, 2, 3]
b = [1, 2, 3]
print(a == b)
print(a is b)

"""###Bitwise and operator"""

print(2 & 3)
print(1 & 1)
print(7 & 8)
print(5 & 1)

"""###Bitwise OR operator"""

print(2 | 3)
print(1 | 1)
print(7 | 8)
print(5 | 1)

"""###Ternary operator"""

num = 7
result = "even" if num % 2 == 0 else "odd"
print(result)

"""###Compound assignment operator"""

x = 5
x *= 3
print(x)
x += 3
print(x)
x -= 3
print(x)
x /= 3
print(x)

"""###Operator precidence"""

w = 3 * 2 - 5 ** 2 * 32 / 7 + 1
print(w)

"""###Membership not in"""

q = 3 not in [1, 2, 3]
print(q)

"""###Logical not"""

d = not (2>3 and 5>4)
print(d)

#Left shift bitwise operator
s = 8>>5
print(s)